---
version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: es01
    ports: 
      - '9200:9200'
    environment:
      - cluster.name=es-cluster01
      - node.name=es01
      - http.port=9200
      - cluster.initial_master_nodes=es01
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: 
      - 'elastic'

  kb01:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kb01
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports: 
      - '5601:5601'
    networks: 
      - 'elastic'
    depends_on: 
      - 'es01'

networks:
  elastic:
    driver: bridge

volumes:
  data01:
